In [ ]:
##ROSHAN KALYANI
##PYTHON VERSION 3.10

In [ ]:
#All credits to 'Scikit-learn: Machine Learning in Python, Pedregosa et al., JMLR 12, pp. 2825-2830, 2011'

In [ ]:
##Remove Hashtag and run to check wether Sklearn is working or not in your local machine

#!pip install sklearn

Here I will Run some features of **sklearn** library.

It has various **classification**, **regression** and **clustering** algorithms. *italicized text*

In [2]:
from sklearn import neighbors,datasets,preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
iris = datasets.load_iris()

In [ ]:
X,y = iris.data[:,:2], iris.target

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(X,y)

In [ ]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [ ]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
knn = neighbors.KNeighborsClassifier(n_neighbors = 5)

In [ ]:
knn.fit(X_train, y_train)

In [ ]:
y_pred = knn.predict(X_test)

In [ ]:
accuracy_score(y_test, y_pred)

0.2894736842105263

In [ ]:
##LOADING

In [3]:
import numpy as np

In [4]:
X = np.random.random((10,5))

In [5]:
X

array([[0.78705957, 0.27352314, 0.85400341, 0.44051438, 0.437271  ],
       [0.33476485, 0.74543572, 0.79474981, 0.5890866 , 0.09224737],
       [0.80583011, 0.67974671, 0.07387495, 0.58771734, 0.78255505],
       [0.63134872, 0.783162  , 0.50327692, 0.57748029, 0.09069891],
       [0.82069576, 0.31104472, 0.36544399, 0.36123895, 0.25649657],
       [0.50635957, 0.13425727, 0.49039498, 0.00367533, 0.93764038],
       [0.25663541, 0.5574212 , 0.68771502, 0.92549973, 0.20180577],
       [0.9270514 , 0.51261626, 0.54065113, 0.26216148, 0.8746133 ],
       [0.05613732, 0.5700696 , 0.57478536, 0.05828137, 0.3221159 ],
       [0.70105786, 0.52897418, 0.05133868, 0.24453389, 0.33814421]])

In [9]:
y = ['A','B','A','A','B','A','A','B','A','A']

In [10]:
y

['A', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A', 'A']

**Training and Testing Dataset**

In [ ]:
from sklearn.model_selection import train_test_split

#spliting train and test dataset
X_train,X_test,y_train,y_test = train_test_split(X,y,
random_state = 0)

**PreProcessing Dataset**

**Standardization** : Standardizes the features by removing the mean and scaling to unit variance.


```
# This is formatted as code
```



In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_train)
standarized_X = scaler.transform(X_train)
standarized_X_test = scaler.transform(X_test)

**Normalization** : Each sample (row of the data matrix) with at least one non-zero component is rescaled independently of other samples so that its norm equals one.


In [ ]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(X_train)
normalized_X = scaler.transform(X_train)
normalized_X_test = scaler.transform(X_test)

**Binarization** : Binarize data (set feature values to 0 or 1) according to a threshold.


In [ ]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold = 0.0).fit(X)
binary_X = binarizer.transform(X_test)

**Encoding Categorical Features** : Imputation transformer for completing missing values.


In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit_transform(X_train)

**Imputing Missing Values** :

In [ ]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=0, strategy ='mean')
imp.fit_transform(X_train)

array([[0.14439921, 0.39604162, 0.67240878, 0.1609183 , 0.76065976],
       [0.75346957, 0.21120363, 0.53475426, 0.65476931, 0.69031367],
       [0.39808265, 0.95251808, 0.7575469 , 0.37602661, 0.56258183],
       [0.73918893, 0.64206855, 0.26834369, 0.92925575, 0.73083936],
       [0.47762379, 0.52892873, 0.91574949, 0.86719635, 0.04729763],
       [0.44475736, 0.30986814, 0.16359246, 0.67815904, 0.99559743],
       [0.23151838, 0.68880048, 0.99544816, 0.15708435, 0.65775932]])

**Generating Polynomial Features** :

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(5)
poly.fit_transform(X)

array([[1.00000000e+00, 4.44757359e-01, 3.09868138e-01, ...,
        4.53852162e-01, 6.66295096e-01, 9.78180105e-01],
       [1.00000000e+00, 7.53469566e-01, 2.11203635e-01, ...,
        1.41031474e-01, 1.48687413e-01, 1.56758958e-01],
       [1.00000000e+00, 2.70789310e-01, 7.33302323e-01, ...,
        5.46952931e-03, 4.25769020e-03, 3.31434842e-03],
       ...,
       [1.00000000e+00, 7.39188933e-01, 6.42068550e-01, ...,
        3.37082570e-01, 2.65108083e-01, 2.08501720e-01],
       [1.00000000e+00, 3.10530376e-01, 6.86968798e-01, ...,
        2.74919422e-04, 3.13187589e-05, 3.56782599e-06],
       [1.00000000e+00, 1.44399209e-01, 3.96041621e-01, ...,
        1.13967811e-02, 5.38725097e-02, 2.54655002e-01]])


**Supervised Learning Models**

In [ ]:
## Linear Regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression(normalize = True)

In [ ]:
## Support Vector Machine (SVM)
from sklearn.svm import SVC
svc = SVC(kernel = 'linear')

In [ ]:
## Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [ ]:
##KNN
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier(n_neighbors = 5)


**UnSupervised Learning Models**

In [ ]:
## Principal Component Analysis (PCA)
from sklearn.decomposition import PCA
pca = PCA(n_components = 0.95)

In [ ]:
## K-means
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters = 3, random_state = 0)

**Model Fitting**

In [ ]:
## Fitting Learning Moddels ( Supervised and Unsupervised )

#Fit the model to the data

lr.fit(X, y)
knn.fit(X_train,y_train)
svc.fit(X_train,y_train)

SVC(kernel='linear')

In [ ]:
k_means.fit(X_train) 
pca_model = pca.fit_transform(X_train)  #Fit to data,then transform

**Prediction**

In [ ]:
#Predicting Label
y_pred = lr.predict(X_test) #Supervised Estimators
y_pred = k_means.predict(X_test) #Unsupervised Estimators

In [ ]:
## Estimate a probability of a label
y_pred = knn.predict_proba(X_test)

**Evaluate Your Model’s Performance** :

**Classification Metrics**

**Accuracy Score** :

In [ ]:
knn.score(X_test,y_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

**Classification Report** :

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

**Confusion Matrix** :

In [ ]:
from sklearn .metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

**Regression Metrics**

**Mean Absolute Error (MAE)** :

In [ ]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

**Mean Squared Error (MSE)**

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

**R² Score**

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

**Clustering Metrics**

**Adjusted Rand Index**

In [ ]:
from sklearn.metrics import adjusted_rand_score
adjusted_rand_score(y_test,y_pred)

**Homogeneity**

In [ ]:
from sklearn.metrics import homogeneity_score
homogeneity_score(y_test,y_pred)

**V-measure**

In [ ]:
from sklearn.metrics import v_measure_score
v_measure_score(y_test,y_pred)

**Tune the Model**

**Grid Search**

In [ ]:
from sklearn.model_selection import GridSearchCV
params = {'n_neighbors':np.arange(1,3),
'metric':['euclidean','cityblock']}
grid = GridSearchCV(estimator = knn, param_grid = params)
grid.fit(X_train, y_train)
print(grid.best_score_)
print(grid.best_estimator_)